# Generated by Django 3.1.2 on 2020-11-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
