# Generated by Django 3.1.2 on 2020-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201127_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profilePicture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
