# Generated by Django 3.1.2 on 2020-11-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
