# Generated by Django 3.1.2 on 2021-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
