# Generated by Django 3.1.3 on 2020-11-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiles',
            table='"Profiles',
        ),
    ]
