# Generated by Django 3.1.3 on 2020-11-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0002_auto_20201104_1332'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiles',
            table='Profiles',
        ),
    ]
