# Generated by Django 3.1.2 on 2020-11-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0003_auto_20201104_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profilePicture',
            field=models.BinaryField(blank=True),
        ),
    ]
