# Generated by Django 3.1.2 on 2020-11-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tag',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
