# Generated by Django 3.1.2 on 2020-11-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('subject',)},
        ),
    ]
