# Generated by Django 3.1.3 on 2021-01-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201127_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('subjectCode',)},
        ),
    ]
